title: Giovani Thai's Homepage
page-top-title: Giovani Thai
top-section-bg-text: Welcome!
home-subtitle: Giovani Thai&ensp;|&ensp; Applied Mathematician
copyright-text: '&copy; Giovani Thai 2024. All Rights Reserved.'
